#!/bin/bash

# Iterar sobre un rango de números
for i in {1..9}; do
    python3 zdt3/zdt3.py
    cat <<EOL > metrics.in
2
1
2
cf6/EVAL10000_4D/P40G2500/cf6_4d_all_popmp40g250_seed0$i.out
40
250
cf6/cf6_all_popm.out
40
250
1
EOL
    ./metrics < metrics.in

done
