#!/bin/bash

# Iterar sobre un rango de números
for i in {1..9}; do
    python3 zdt3/zdt3.py
    cat <<EOL > metrics.in
2
1
2
cf6/EVAL10000_4D/P200G50/cf6_4d_all_popmp200g50_seed0$i.out
200
50
cf6/cf6_all_popm.out
200
50
1
EOL
    ./metrics < metrics.in

done
