#!/bin/bash

# Iterar sobre un rango de números
for i in {1..9}; do
    python3 cf6/cf6.py
    cat <<EOL > metrics.in
2
1
2
cf6/EVAL10000_4D/P100G100/cf6_4d_all_popmp100g100_seed0$i.out
100
100
cf6/cf6_all_popm.out
100
100
1
EOL
    ./metrics < metrics.in

done
