#!/bin/bash

# Iterar sobre un rango de números
for i in {1..9}; do
    python3 zdt3/zdt3.py
    cat <<EOL > metrics.in
2
1
2
EVAL10000/P100G100/zdt3_all_popmp100g100_seed0$i.out
100
100
zdt3/zdt3_all_popm.out
100
100
1
EOL
    ./metrics < metrics.in 2> error.log || true &
    python3 plot_metrics.py

done
