#!/bin/bash

# Iterar sobre un rango de números
for i in {1..9}; do
    python3 zdt3/zdt3.py
    cat <<EOL > metrics.in
2
1
2
zdt3/EVAL10000/P40G250/zdt3_all_popmp40g250_seed0$i.out
250
40
zdt3/zdt3_all_popm.out
250
40
1
EOL
    ./metrics < metrics.in 2> error.log || true &
    python3 plot_metrics.py

done
